name: Nullstone
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Package files into tgz
      - name: Package
        run: tar -cvzf module.tgz *.tf

      - name: Find version
        id: version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

      # Publish to nullstone
      - name: Publish
        env:
          RELEASE_VERSION: ${{ steps.version.outputs.tag }}
        run: |-
          curl -XPOST -F "file=@module.tgz" -H "X-Nullstone-Key: ${{ secrets.NULLSTONE_API_KEY }}" \
            https://api.nullstone.io/orgs/nullstone/modules/aws-network/versions?version=${RELEASE_VERSION}
